const NodePodsDataSet = () => ({
  selection: false,
  pageSize: 10,
  data: [{
    id: 73636,
    name: 'manager-service-devx-657bd998c-pp6dj',
    ip: '10.244.0.99',
    status: 'Running',
    creationDate: '2019-08-22 10:39:04',
    appName: null,
    namespace: 'devx',
    appVersion: null,
    publishLevel: null,
    instanceCode: null,
    envId: null,
    projectId: null,
    envCode: null,
    envName: null,
    objectVersionNumber: 5,
    clusterId: null,
    containers: null,
    nodeName: '192.168.100.27',
    restartCount: 0,
    containersForLogs: [{
      podName: 'manager-service-devx-657bd998c-pp6dj',
      containerName: 'manager-service-devx',
      logId: 'ad27211a-7cde-4e81-9d90-ac8cad200c48',
    }],
    ready: true,
    connect: null,
  }, {
    id: 73357,
    name: 'asgard-service-6df7c5678-qqn29',
    ip: '10.244.0.83',
    status: 'Running',
    creationDate: '2019-08-21 12:03:56',
    appName: null,
    namespace: 'devx',
    appVersion: null,
    publishLevel: null,
    instanceCode: null,
    envId: null,
    projectId: null,
    envCode: null,
    envName: null,
    objectVersionNumber: 5,
    clusterId: null,
    containers: null,
    nodeName: '192.168.100.27',
    restartCount: 0,
    containersForLogs: [{
      podName: 'asgard-service-6df7c5678-qqn29',
      containerName: 'asgard-service',
      logId: '0858365b-eb89-480d-958b-ecf226fbb196',
    }],
    ready: true,
    connect: null,
  }],
  transport: {
    read: {
      method: 'post',
      url: 'devops/v1/organizations/{projectId}/clusters/page_node_pods?cluster_id=?&node_name=?',
    },
  },
});

export default NodePodsDataSet;
