export default (projectId) => ({
  autoCreate: true,
  fields: [{
    name: 'type',
    type: 'string',
    label: '任务类型',
    required: true,
    defaultValue: 'cdDeploy',
  }, {
    name: 'name',
    type: 'string',
    label: '任务名称',
    required: true,
  }, {
    name: 'glyyfw',
    type: 'string',
    label: '关联应用服务',
    required: true,
    disabled: true,
  }, {
    name: 'triggerType',
    type: 'string',
    label: '匹配类型',
    required: true,
    defaultValue: 'refs',
  }, {
    name: 'triggerValue',
    type: 'string',
    label: '触发分支',
  }, {
    name: 'envId',
    type: 'string',
    label: '环境名称',
    required: true,
    textField: 'name',
    valueField: 'id',
    lookupAxiosConfig: () => ({
      method: 'get',
      url: `/devops/v1/projects/${projectId}/envs/list_by_active?active=true`,
    }),
  }, {
    name: 'bsms',
    type: 'string',
    label: '部署模式',
    defaultValue: 'new',
  }, {
    name: 'instanceName',
    type: 'string',
    label: '实例名称',
    required: true,
  }, {
    name: 'instanceId',
    type: 'string',
    label: '选择要替换的实例',
    required: true,
  }, {
    name: 'valueId',
    type: 'string',
    label: '部署配置',
    required: true,
  }, {
    name: 'hostIp',
    type: 'string',
    label: 'IP',
    required: true,
  }, {
    name: 'hostPort',
    type: 'string',
    label: '端口',
    required: true,
  }, {
    name: 'accountType',
    type: 'string',
    label: '账号配置',
    defaultValue: 'accountPassword',
  }, {
    name: 'userName',
    type: 'string',
    label: '用户名',
    required: true,
  }, {
    name: 'password',
    type: 'string',
    label: '密码',
    required: true,
  }, {
    name: 'accountKey',
    type: 'string',
    label: '密钥',
    required: true,
  }, {
    name: 'mode',
    type: 'string',
    label: '部署模式',
    defaultValue: 'customize',
  }, {
    name: 'repoName',
    type: 'string',
    label: '项目镜像仓库',
    required: true,
  }, {
    name: 'imageName',
    type: 'string',
    label: '镜像',
    required: true,
  }, {
    name: 'matchType',
    type: 'string',
    label: '匹配类型',
    required: true,
  }, {
    name: 'matchContent',
    type: 'string',
    label: '镜像版本匹配',
    required: true,
  }, {
    name: 'serverName',
    type: 'string',
    label: 'Nexus服务',
    required: true,
  }, {
    name: 'neRepositoryName',
    type: 'string',
    label: '项目制品库',
    required: true,
  }, {
    name: 'groupId',
    type: 'string',
    label: 'groupID',
    required: true,
  }, {
    name: 'artifactId',
    type: 'string',
    label: 'artifactID',
    required: true,
  }, {
    name: 'versionRegular',
    type: 'string',
    label: 'jar包版本正则匹配',
    required: true,
  }, {
    name: 'cdAuditUserIds',
    type: 'string',
    label: '审核人员',
    required: true,
  }, {
    name: 'countersigned',
    type: 'string',
    label: '审核模式',
    required: true,
  }],
});
