# devops-base镜像的dockerfile
FROM ubuntu:18.04 as pyinstaller
WORKDIR /home/yaml
COPY values_yaml.py ./
RUN apt-get update; \
    apt-get install python3-pip -y
RUN pip3 install --upgrade pip
RUN pip3 install pyinstaller ruamel.yaml==0.16.12
RUN pyinstaller --noconfirm --clean values_yaml.py

FROM busybox
COPY --from=pyinstaller /home/yaml/dist/values_yaml /usr/lib/yaml