FROM registry.cn-shanghai.aliyuncs.com/choerodon-tools/devops-base:0.7.2 as pyinstaller
FROM registry.cn-shanghai.aliyuncs.com/choerodon-tools/javabase:0.8.2
COPY --from=pyinstaller /home/yaml/dist/values_yaml /usr/lib/yaml
COPY --from=pyinstaller /usr/bin/kaniko /usr/bin/kaniko
COPY app.jar /devops-service.jar
COPY dist /dist
RUN chmod 777 /dist/env.sh
CMD /dist/env.sh java $JAVA_OPTS $SKYWALKING_OPTS -jar /devops-service.jar
