# devops-base镜像的dockerfile
FROM gcr.azk8s.cn/kaniko-project/executor:v0.11.0
FROM dockerhub.azk8s.cn/cdrx/pyinstaller-linux:python3

WORKDIR /home/yaml
COPY values_yaml.py ./
RUN pip3 install --no-cache-dir ruamel.yaml==0.15.54 -i https://mirrors.aliyun.com/pypi/simple/
RUN pyinstaller --noconfirm --clean values_yaml.py

# Install kaniko
COPY --from=0 /kaniko/executor /usr/bin/kaniko