export default () => ({
  autoCreate: true,
  fields: [{
    name: 'rwlx',
    type: 'string',
    label: '任务类型',
    require: true,
    defaultValue: 'gj',
  }, {
    name: 'rwmc',
    type: 'string',
    label: '任务名称',
    require: true,
  }, {
    name: 'glyyfw',
    type: 'string',
    label: '关联应用服务',
    require: true,
  }, {
    name: 'cffzlx',
    type: 'string',
    label: '触发分支类型',
  }, {
    name: 'gjmb',
    type: 'string',
    label: '构建模板',
  }, {
    name: 'bzmc',
    type: 'string',
    label: '步骤名称',
    require: true,
  }, {
    name: 'yhm',
    type: 'string',
    label: '用户名',
    require: true,
  }, {
    name: 'mm',
    type: 'string',
    label: '密码',
  }, {
    name: 'gjblj',
    type: 'string',
    label: '构建包路径',
    require: true,
  }, {
    name: 'sonarQube',
    type: 'string',
    label: 'SonarQube',
    defaultValue: 'M',
  }, {
    name: 'sqyhm',
    type: 'string',
    label: 'SonarQube用户名',
    require: true,
  }, {
    name: 'sqmm',
    type: 'string',
    label: '密码',
  }, {
    name: 'sqdz',
    type: 'string',
    label: 'SonarQube地址',
    require: true,
  }, {
    name: 'token',
    type: 'string',
    label: 'Token',
    require: true,
  }],
});
